name: Conditional Demo
on:
  push:
    branches: [main]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$github.ref"
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/main'
    steps:
      - run: echo "Deploying to production"
